/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#ffb1c4',
        'primary-container': '#ff4a8d',
        'on-primary': '#65002e',
        'primary-fixed': '#ffd9e1',
        'primary-fixed-dim': '#ffb1c4',
        'on-primary-fixed': '#3f001a',
        'on-primary-fixed-variant': '#8f0044',
        'inverse-primary': '#ba005b',
        secondary: '#ffb4a8',
        'secondary-container': '#ce0301',
        'secondary-fixed': '#ffdad4',
        'secondary-fixed-dim': '#ffb4a8',
        'on-secondary': '#690000',
        'on-secondary-fixed': '#410000',
        'on-secondary-fixed-variant': '#930000',
        'on-secondary-container': '#ffdcd7',
        tertiary: '#c6c6c7',
        'tertiary-container': '#909191',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary': '#2f3131',
        'on-tertiary-container': '#282a2a',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        background: '#000000',
        'on-background': '#e2e2e2',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1b1b',
        'surface-container': '#1f1f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'surface-variant': '#353535',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#e5bcc5',
        'surface-tint': '#ffb1c4',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#303030',
        outline: '#ac878f',
        'outline-variant': '#5c3f46',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'data-lg': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-sm': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '500' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '500' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.1', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '400' }],
        'data-lg': ['32px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
      spacing: {
        'grid-unit': '8px',
        'margin-mobile': '24px',
        'margin-desktop': '64px',
        'gutter': '24px',
        'section-gap': '128px',
        'container-max': '1440px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      backgroundSize: {
        'grid': '80px 80px',
      },
    },
  },
  plugins: [],
}
