#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const extracted = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const outDir = process.argv[3] || '/opt/mizpa/output/react-app';
fs.mkdirSync(outDir, { recursive: true });
fs.mkdirSync(path.join(outDir, 'src'), { recursive: true });
const appTsx = `import React from 'react';
export default function App() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow">
        <div className="max-w-7xl mx-auto px-4 py-6">
          <h1 className="text-3xl font-bold text-gray-900">${extracted.title || 'Generated Page'}</h1>
          ${extracted.description ? `<p className="mt-2 text-gray-600">${extracted.description}</p>` : ''}
        </div>
      </header>
      <main className="max-w-7xl mx-auto px-4 py-8">
        <p className="text-gray-700">Generated by Mizpa Agent</p>
      </main>
    </div>
  );
}`;
fs.writeFileSync(path.join(outDir, 'src/App.tsx'), appTsx);
const pkg = { name: 'mizpa-generated', private: true, version: '0.0.1',
  scripts: { dev: 'vite', build: 'vite build' },
  dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0' },
  devDependencies: { '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
    '@vitejs/plugin-react': '^4.3.0', autoprefixer: '^10.4.0', postcss: '^8.4.0',
    tailwindcss: '^3.4.0', typescript: '^5.6.0', vite: '^6.0.0' }
};
fs.writeFileSync(path.join(outDir, 'package.json'), JSON.stringify(pkg, null, 2));
console.log(JSON.stringify({ status: 'generated', outputDir: outDir, files: ['src/App.tsx', 'package.json'] }));
